var searchData=
[
  ['baseexception',['BaseException',['../class_you_1_1_exception_1_1_base_exception.html',1,'You::Exception']]],
  ['baseexception',['BaseException',['../class_you_1_1_query_engine_1_1_exception_1_1_base_exception.html',1,'You::QueryEngine::Exception']]],
  ['basemanager',['BaseManager',['../class_you_1_1_g_u_i_1_1_main_window_1_1_base_manager.html#ab8a7839b21f9b952f30ccab1757248e6',1,'You::GUI::MainWindow::BaseManager']]],
  ['basemanager',['BaseManager',['../class_you_1_1_g_u_i_1_1_main_window_1_1_base_manager.html',1,'You::GUI::MainWindow']]],
  ['batch_5fadd_5fsubtasks_2eh',['batch_add_subtasks.h',['../batch__add__subtasks_8h.html',1,'']]],
  ['batchadddependencies',['BatchAddDependencies',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_dependencies.html',1,'You::QueryEngine::Internal::Action']]],
  ['batchadddependencies',['BatchAddDependencies',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_dependencies.html#ae3d282162a20953d8fa7ef7b963d5519',1,'You::QueryEngine::Internal::Action::BatchAddDependencies::BatchAddDependencies(const Task::Description &amp;description, const Task::Time &amp;startTime, const Task::Time &amp;deadline, const Task::Priority &amp;priority, std::vector&lt; std::unique_ptr&lt; Query &gt;&gt; &amp;&amp;dependencies, const Task::Subtasks &amp;subtasks)'],['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_dependencies.html#a5856a690fa80ca8eabb318c4de35100c',1,'You::QueryEngine::Internal::Action::BatchAddDependencies::BatchAddDependencies(Task::ID id, const Task::Description &amp;description, const Task::Time &amp;startTime, const Task::Time &amp;deadline, const Task::Priority &amp;priority, std::vector&lt; std::unique_ptr&lt; Query &gt;&gt; &amp;&amp;dependencies, const Task::Subtasks subtasks)']]],
  ['batchaddsubtasks',['BatchAddSubTasks',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_sub_tasks.html',1,'You::QueryEngine::Internal::Action']]],
  ['batchaddsubtasks',['BatchAddSubTasks',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_sub_tasks.html#a7afedb7e685dcbc7ef51b54e58ad08ce',1,'You::QueryEngine::Internal::Action::BatchAddSubTasks::BatchAddSubTasks(const Task::Description &amp;description, const Task::Time &amp;startTime, const Task::Time &amp;deadline, const Task::Priority &amp;priority, const Task::Dependencies &amp;dependencies, std::vector&lt; std::unique_ptr&lt; Query &gt;&gt; &amp;&amp;subtasks)'],['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_batch_add_sub_tasks.html#a4240defae7e417e0ff8bd717823213eb',1,'You::QueryEngine::Internal::Action::BatchAddSubTasks::BatchAddSubTasks(Task::ID id, const Task::Description &amp;description, const Task::Time &amp;startTime, const Task::Time &amp;deadline, const Task::Priority &amp;priority, const Task::Dependencies &amp;dependencies, std::vector&lt; std::unique_ptr&lt; Query &gt;&gt; &amp;&amp;subtasks)']]],
  ['begin',['begin',['../class_you_1_1_data_store_1_1_data_store.html#a7c4eacbf887da527cbf5927569fc43cb',1,'You::DataStore::DataStore::begin()'],['../class_you_1_1_data_store_1_1_internal_1_1_data_store.html#ada496918b1cc5429fd4b1c16a11700b0',1,'You::DataStore::Internal::DataStore::begin()']]],
  ['begintransactionaddstotransactionstack',['beginTransactionAddsToTransactionStack',['../class_you_1_1_data_store_1_1_unit_tests_1_1_data_store_test.html#a0bcc76a150e4649442b560aca0d3dff3',1,'You::DataStore::UnitTests::DataStoreTest']]],
  ['branchname',['branchName',['../class_you_1_1_data_store_1_1_internal_1_1_operation.html#a20d0dd6a5b84fa403e8cd7df59d9b8cc',1,'You::DataStore::Internal::Operation']]],
  ['branchoperation',['BranchOperation',['../class_you_1_1_data_store_1_1_internal_1_1_branch_operation.html',1,'You::DataStore::Internal']]],
  ['builder',['Builder',['../class_you_1_1_query_engine_1_1_internal_1_1_controller.html#a9a972ecd8bcbd88f971c3183d6a848c5',1,'You::QueryEngine::Internal::Controller']]],
  ['butnot',['butNot',['../class_you_1_1_query_engine_1_1_filter.html#a955ab7a0d5bfb4b220a04d45dfaeada1',1,'You::QueryEngine::Filter']]],
  ['bydeadline',['byDeadline',['../class_you_1_1_query_engine_1_1_comparator.html#a9028cfe210e530090291c3c9b8d5ff13',1,'You::QueryEngine::Comparator']]],
  ['bydependenciescount',['byDependenciesCount',['../class_you_1_1_query_engine_1_1_comparator.html#aa0a80bac2bfa204b1bd6a8357a9d5efc',1,'You::QueryEngine::Comparator']]],
  ['bydescription',['byDescription',['../class_you_1_1_query_engine_1_1_comparator.html#a6fecd1bb3fe6437124c97b6a916e1391',1,'You::QueryEngine::Comparator']]],
  ['bypriority',['byPriority',['../class_you_1_1_query_engine_1_1_comparator.html#a34fc507091520031b8fbd07acb131c32',1,'You::QueryEngine::Comparator']]],
  ['byrelationship',['byRelationship',['../class_you_1_1_query_engine_1_1_comparator.html#ae321a10ad37d994543cd6ee461c10691',1,'You::QueryEngine::Comparator']]]
];
