var searchData=
[
  ['datastoretest',['DataStoreTest',['../class_you_1_1_data_store_1_1_internal_1_1_data_store.html#a0ac69b7bacd7b2f194d5536a18b42c83',1,'You::DataStore::Internal::DataStore']]],
  ['undo',['Undo',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_undo.html',1,'You::QueryEngine::Internal::Action']]],
  ['undo',['Undo',['../class_you_1_1_query_engine_1_1_query_engine.html#a5a9ffc039b17b76152e5a626d5ef90b9',1,'You::QueryEngine::QueryEngine::Undo()'],['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_undo.html#a4260b2a4ca7e6b38574a8a0cc1a9ed6a',1,'You::QueryEngine::Internal::Action::Undo::Undo()']]],
  ['undo_2eh',['undo.h',['../undo_8h.html',1,'']]],
  ['undo_5fquery',['UNDO_QUERY',['../struct_you_1_1_n_l_p_1_1_u_n_d_o___q_u_e_r_y.html',1,'You::NLP']]],
  ['undo_5fresult',['UNDO_RESULT',['../struct_you_1_1_controller_1_1_u_n_d_o___r_e_s_u_l_t.html',1,'You::Controller']]],
  ['undostack',['undoStack',['../class_you_1_1_query_engine_1_1_internal_1_1_state.html#a11f44ca43703c4778a9b94894bc57210',1,'You::QueryEngine::Internal::State']]],
  ['update_5ftask_2eh',['update_task.h',['../update__task_8h.html',1,'']]],
  ['updatetask',['UpdateTask',['../class_you_1_1_query_engine_1_1_query_engine.html#a22d42becad882ba07229bf812f38f718',1,'You::QueryEngine::QueryEngine::UpdateTask(Task::ID id, Option&lt; Task::Description &gt; description, Option&lt; Task::Time &gt; startTime, Option&lt; Task::Time &gt; deadline, Option&lt; Task::Priority &gt; priority, Delta&lt; Task::Dependencies::value_type &gt; dependencies, Option&lt; bool &gt; completed, Option&lt; Task::ID &gt; parent, Delta&lt; Task::Subtasks::value_type &gt; subtasks, Delta&lt; Task::Attachment::value_type &gt; attachment)'],['../class_you_1_1_query_engine_1_1_query_engine.html#aa7644892695a815875704a3c1e45b929',1,'You::QueryEngine::QueryEngine::UpdateTask(const Task &amp;task)'],['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_update_task.html#a2a496c6bb03512a2707812957a72acb1',1,'You::QueryEngine::Internal::Action::UpdateTask::UpdateTask(Task::ID id, You::Utils::Option&lt; Task::Description &gt; description, You::Utils::Option&lt; Task::Time &gt; startTime, You::Utils::Option&lt; Task::Time &gt; deadline, You::Utils::Option&lt; Task::Priority &gt; priority, You::Utils::Option&lt; Task::Dependencies &gt; dependencies, You::Utils::Option&lt; bool &gt; completed, You::Utils::Option&lt; Task::ID &gt; parent, You::Utils::Option&lt; Task::Subtasks &gt; subtasks, You::Utils::Option&lt; Task::Attachment &gt; attachment)'],['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_update_task.html#a167853aace48a1d5614e3f171fe0bbdd',1,'You::QueryEngine::Internal::Action::UpdateTask::UpdateTask(const Task &amp;task)'],['../class_you_1_1_query_engine_1_1_internal_1_1_task_graph_controller.html#ad7f17fc7ce3f54c7eb841cda428317f8',1,'You::QueryEngine::Internal::TaskGraphController::updateTask()']]],
  ['updatetask',['UpdateTask',['../class_you_1_1_query_engine_1_1_internal_1_1_action_1_1_update_task.html',1,'You::QueryEngine::Internal::Action']]]
];
